ALTER TABLE code ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE code ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE code SET created_at = NOW() WHERE created_at IS NULL;
UPDATE code SET updated_at = NOW() WHERE updated_at IS NULL;