name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: daehyeong2010/sh4re
          stage: main
          yaml: >
            name: sh4re-server

            app: java@17

            options:
              ports: ${{ secrets.PORT }}
              env:
                - name: DATABASE_URL
                  value: ${{ secrets.DATABASE_URL }}
                - name: DATABASE_USERNAME
                  value: ${{ secrets.DATABASE_USERNAME }}
                - name: DATABASE_PASSWORD
                  value: ${{ secrets.DATABASE_PASSWORD }}
                - name: PORT
                  value: ${{ secrets.PORT }}
                - name: JWT_SECRET_KEY
                  value: ${{ secrets.JWT_SECRET_KEY }}
                - name: IS_DEVELOPMENT
                  value: ${{ secrets.IS_DEVELOPMENT }}
                - name: OPENAI_API_KEY
                  value: ${{ secrets.OPENAI_API_KEY }}
                - name: TZ
                  value: Asia/Seoul
                - name: IS_DEVELOPMENT
                  value: false
              buildenv: []
              start: java -Xms512M -Xmx1G -jar ./build/libs/sh4re-0.0.1-SNAPSHOT.jar
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: java-springboot